# Generated by Django 4.1.2 on 2022-11-19 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="nickname",
            field=models.CharField(blank=True, default="", max_length=128, null=True),
        ),
    ]
